export const STRINGS = {
  zh: {
    appTitle: 'HK SOUNDS',
    home: '主頁',
    favourites: '我的最愛',
    settings: '設定',
    add: '新增',
    all: '全部',
    emptySound: '未有聲音',
    emptySoundSub: '撳右上角 ＋ 新增聲音',
    emptyFav: '空列表',
    emptyFavSub: '未有最愛！撳任何聲音嘅星星將佢加入呢度。✨',
    showEnglishLabel: '顯示英文標籤',
    showEnglishLabelDesc: '喺中文標籤下面顯示英文翻譯',
    stopOnSecondTap: '再撳停止',
    stopOnSecondTapDesc: '再撳一次停止播放中嘅聲音',
    settingsTitle: '設定',
    deleteTitle: '刪除聲音',
    deleteConfirm: '確定刪除',
    cancel: '取消',
    delete: '刪除',
    langToggle: 'EN',
    addSound: '新增聲音',
    back: '← 返回',
    mp3Label: 'MP3 檔案',
    mp3Placeholder: '撳此選擇 MP3 檔案',
    labelZh: '標籤（中文）',
    labelEn: '標籤（英文，可選）',
    emojiLabel: 'Emoji',
    categoryLabel: '類別',
    saveBtn: '儲存聲音',
    saving: '儲存中...',
    missingLabel: '請輸入標籤',
    missingEmoji: '請輸入 Emoji',
    missingFile: '請選擇 MP3 檔案',
    errorSave: '無法儲存聲音',
    catCantonese: '粵語',
    catMeme: '迷因',
    catReaction: '反應',
    catMovie: '電影橋段',
    catSituation: '情景',
  },
  en: {
    appTitle: 'HK SOUNDS',
    home: 'HOME',
    favourites: 'FAVOURITES',
    settings: 'SETTINGS',
    add: 'ADD',
    all: 'ALL',
    emptySound: 'No sounds yet',
    emptySoundSub: 'Tap + to add a sound',
    emptyFav: 'Empty List',
    emptyFavSub: 'No favourites yet! Tap the star on any sound to add it here. ✨',
    showEnglishLabel: 'Show English Labels',
    showEnglishLabelDesc: 'Display English translation below Chinese label',
    stopOnSecondTap: 'Stop on Second Tap',
    stopOnSecondTapDesc: 'Tap a playing sound again to stop it',
    settingsTitle: 'SETTINGS',
    deleteTitle: 'Delete Sound',
    deleteConfirm: 'Are you sure you want to delete',
    cancel: 'Cancel',
    delete: 'Delete',
    langToggle: '中',
    addSound: 'Add Sound',
    back: '← Back',
    mp3Label: 'MP3 File',
    mp3Placeholder: 'Tap to select MP3 file',
    labelZh: 'Label (Chinese)',
    labelEn: 'Label (English, optional)',
    emojiLabel: 'Emoji',
    categoryLabel: 'Category',
    saveBtn: 'Save Sound',
    saving: 'Saving...',
    missingLabel: 'Please enter a label',
    missingEmoji: 'Please enter an emoji',
    missingFile: 'Please select an MP3 file',
    errorSave: 'Could not save sound',
    catCantonese: 'Canto',
    catMeme: 'Meme',
    catReaction: 'Reaction',
    catMovie: 'Movie',
    catSituation: 'Situation',
  },
};